---
collections:
  - name: f5networks.f5_modules
    version: 1.31.0
  - name: f5networks.f5_bigip
    version: 3.7.0
  - name: ansible.netcommon
    version: 7.1.0
  - name: ansible.platform
    version: 2.5.3
  - name: ansible.hub
    version: 1.0.0
  - name: ansible.controller
    version: 4.6.2
  - name: ansible.eda
    version: 2.2.0
  - name: infra.aap_configuration
    version: 3.1.0
