- name: First thing lets do is get the Ec2 info
  amazon.aws.ec2_instance_info:
    instance_ids:
      - i-06659bba1f9895a7e
    region: "{{ scale_up_region }}"
  register: new_node_info

- name: Lets dump out the Ec2 info
  ansible.builtin.debug:
    var: new_node_info.instances[0].instance_id

- name: Block to setup the webserver
  vars:
    additional_webserver_instance_id: "i-06659bba1f9895a7e"
  when: new_node_info.instances[0].instance_id == additional_webserver_instance_id
  block:
    - name: Install the latest version of Firewalld, Apache
      ansible.builtin.dnf:
        name:
          - firewalld
          - httpd
        state: present

    - name: Starting Firewalld
      ansible.builtin.systemd:
        state: started
        name: firewalld
        enabled: true

    - name: Add a block in httpd.conf for server-status / Instana monitoring
      ansible.builtin.blockinfile:
        path: /etc/httpd/conf/httpd.conf
        append_newline: true
        prepend_newline: true
        insertafter: ^ServerRoot "/etc/httpd"
        block: |
          <Location /server-status>
            SetHandler server-status
          </Location>
          ExtendedStatus On
        state: present
      notify: restart_instana_agent

    - name: Starting httpd
      ansible.builtin.systemd:
        state: started
        name: httpd
        enabled: true

    - name: Update the firewall for port 80
      ansible.posix.firewalld:
        service: http
        permanent: true
        state: enabled
        immediate: true
        zone: public

    - name: Copy the image file for the website
      ansible.builtin.copy:
        src: images/aap.png
        dest: /var/www/html/aap.png
        owner: root
        group: root
        mode: u+rw,g-wx,o-wx

    - name: Copy the image file for the website
      ansible.builtin.copy:
        src: images/AmesQNRCode.png
        dest: /var/www/html/AmesQNRCode.png
        owner: root
        group: root
        mode: u+rw,g-wx,o-wx

    - name: Copy the index.html for the website
      ansible.builtin.template:
        src: index_html_aapdemo.j2
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: u+rw,g-wx,o-wx

    - name: Restart the webserver
      ansible.builtin.service:
        name: httpd
        state: restarted
