---
authors:
  - Eric Ames (ericcames)
  - Mark Lowcher (mlowcher61)
dependencies:
  "amazon.aws": ">=7.2.0"
  "ansible.posix": ">=1.6.2"
  "ansible.utils": ">=5.1.2"
  "ansible.platform": ">=2.5.3"
  "ansible.hub": ">=1.0.0"
  "ansible.controller": ">=4.6.2"
  "ansible.eda": ">=2.2.0"
  "infra.aap_configuration": ">=3.1.0"
license_file: LICENSE
name: f5dailydemo
description: An f5 demo that can be run every day to show people how Ansible Automation Platform can be used to manage f5 devices.
namespace: ericcames
readme: README.md
repository: https://github.com/ericcames/aap.dailydemo.F5
issues: https://github.com/ericcames/aap.dailydemo.F5/issues
tags:
  - lab
  - cloud
  - aws
  - f5
  - dailydemo
version: 0.0.0