---
controller_credentials:
  - name: AWS Credential
    organization: "{{ my_organization }}"
    credential_type: Amazon Web Services
    inputs:
      username: "{{ aws_access_key }}"
      password: "{{ aws_secret_key }}"

  - name: Daily Demo F5
    description: ssh key based authentication
    organization: "{{ my_organization }}"
    credential_type: Machine
    inputs:
      username: admin
      ssh_key_data: "{{ ssh_priv_key }}"

  - name: Daily Demo F5 Network
    description: Userid and password
    organization: "{{ my_organization }}"
    credential_type: Network
    inputs:
      username: admin
      password: "{{ admin_password }}"
