---
controller_workflows:
-   name: "workflow - F5-0-AWS Add custom profiles"
    organization: "{{ my_organization }}"
    related:
      workflow_nodes:
      -   identifier: "F5 -1- AWS -Import certificate and key"
          related:
            success_nodes:
            -   identifier: "F5 -2- AWS -Create custom clientssl"
          unified_job_template:
              name: "F5 -1- AWS -Import certificate and key"
              organization:
                name: "{{ my_organization }}"
              type: job_template
      -   identifier: "F5 -2- AWS -Create custom clientssl"
          related:
            success_nodes:
            -   identifier: "F5 -2- AWS -Create custom TCP profile"
          unified_job_template:
            name: "F5 -2- AWS -Create custom clientssl"
            organization:
              name: "{{ my_organization }}"
            type: job_template
      -   identifier: "F5 -2- AWS -Create custom TCP profile"
          related:
            success_nodes:
            -   identifier: "F5 -2- AWS -Add custom HTTP profile"
          unified_job_template:
            name: "F5 -2- AWS -Create custom TCP profile"
            organization:
              name: "{{ my_organization }}"
            type: job_template
      -   identifier: "F5 -2- AWS -Add custom HTTP profile"
          unified_job_template:
            name: "F5 -2- AWS -Add custom HTTP profile"
            organization:
              name: "{{ my_organization }}"
            type: job_template

-   name: workflow - 0 - Deploy web app on F5 in AWS
    organization: "{{ my_organization }}"
    related:
      workflow_nodes:
      -   identifier: "workflow - F5-0-AWS Add custom profiles"
          related:
            success_nodes:
            -   identifier: "F5 -3- AWS -Add pool and members"
          unified_job_template:
              name: "workflow - F5-0-AWS Add custom profiles"
              organization:
                name: "{{ my_organization }}"
              type: worflow_job_template
      -   identifier: "F5 -3- AWS -Add pool and members"
          related:
            success_nodes:
            -   identifier: "F5 -4- AWS -Create VIP"
          unified_job_template:
            name: "F5 -3- AWS -Add pool and members"
            organization:
              name: "{{ my_organization }}"
            type: job_template
      -   identifier: "F5 -4- AWS -Create VIP"
          unified_job_template:
            name: "F5 -4- AWS -Create VIP"
            organization:
              name: "{{ my_organization }}"
            type: job_template
