---
controller_credentials:
  - name: Daily Demo F5
    description: ssh key based authentication
    organization: "{{ my_organization }}"
    credential_type: Machine
    inputs:
      username: admin
      ssh_key_data: "{{ ssh_priv_key }}"

  - name: Daily Demo F5 Network
    description: Userid and password
    organization: "{{ my_organization }}"
    credential_type: Network
    inputs:
      username: admin
      password: "{{ admin_password }}"

  - name: F5 Demo
    organization: "{{ my_organization }}"
    credential_type: Vault
    inputs:
      vault_password: "{{ f5_vault_passwd }}"