---
controller_schedules:
  - name: Daily Demo F5 auto delete
    description: Schedule to run the demo playbook once a day at 6:00 pm
    rrule: DTSTART;TZID=America/Phoenix:20230101T180000 RRULE:FREQ=DAILY;INTERVAL=1
    unified_job_template: "Daily Demo F5 Create/Remove"
    state: present
    job_tags: remove
    extra_data:
      password: "{{ admin_password }}"
