---
user_message:
  - Hello World

controller_projects:
  - name: mlowcher_F5_examples
    organization: "{{ my_organization }}"
    scm_type: git
    wait: true
    scm_url: https://gitlab.com/mlowcher/F5_examples.git
