---
- name: Install the latest version of Firewalld, Apache
  ansible.builtin.dnf:
    name:
      - firewalld
      - httpd
      - stress-ng
    state: present

- name: Starting Firewalld
  ansible.builtin.systemd:
    state: started
    name: firewalld
    enabled: true

- name: Add a block in httpd.conf for server-status / Instana monitoring
  ansible.builtin.blockinfile:
    path: /etc/httpd/conf/httpd.conf
    append_newline: true
    prepend_newline: true
    insertafter: ^ServerRoot "/etc/httpd"
    block: |
      <Location /server-status>
        SetHandler server-status
      </Location>
      ExtendedStatus On
    state: present

- name: Starting httpd
  ansible.builtin.systemd:
    state: started
    name: httpd
    enabled: true

- name: Update the firewall for port 80
  ansible.posix.firewalld:
    service: http
    permanent: true
    state: enabled
    immediate: true
    zone: public

- name: Copy the image file for the website
  ansible.builtin.copy:
    src: images/aap.png
    dest: /var/www/html/aap.png
    owner: root
    group: root
    mode: u+rw,g-wx,o-wx
  notify: restart_webserver

- name: Copy the image file for the website
  ansible.builtin.copy:
    src: images/AmesQNRCode.png
    dest: /var/www/html/AmesQNRCode.png
    owner: root
    group: root
    mode: u+rw,g-wx,o-wx
  notify: restart_webserver

- name: Copy the index.html for the website
  ansible.builtin.template:
    src: index_html_aapdemo.j2
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: u+rw,g-wx,o-wx
  notify: restart_webserver

- name: Edit the instana configuration file to turn on the http sensor
  ansible.builtin.blockinfile:
    path: /opt/instana/agent/etc/instana/configuration.yaml
    insertafter: "^#com.instana.plugin.action.http: |
                      enabled: true"
    block: |
        com.instana.plugin.action.http:
          enabled: true
    state: present
  notify: restart_instana_agent
