---
- name: Install and configure the Instana APM Agent on Webservers
  hosts: tag_Type_ml_demo
  become: true

  tasks:

    # - name: Install the Instana Agent
    #   ansible.builtin.command: curl -o setup_agent.sh https://setup.instana.io/agent && chmod 700 ./setup_agent.sh && sudo ./setup_agent.sh -a 5fkVYVSVS8O7S9wWgAtUgQ -d 5fkVYVSVS8O7S9wWgAtUgQ -t dynamic -e ingress-coral-saas.instana.io:443 -s

    - name: Insert the httpd configuration directive
      ansible.builtin.blockinfile:
        path: /etc/httpd/conf/httpd.conf
        insertafter: ^ServerRoot "/etc/httpd"
        block: |
          <Location /server-status>
            SetHandler server-status
          </Location>
          LoadModule status_module modules/mod_status.so
          ExtendedStatus On
