---
- name: Create our F5 daily demo
  hosts: localhost
  connection: local

  tasks:

    - name: Include the vpc role
      tags:
        - createvpc
      ansible.builtin.include_role:
        name: vpc

    - name: Include the vm role
      tags:
        - createvm
      ansible.builtin.include_role:
        name: vm

    - name: Include the inventory role
      tags:
        - inventoryadd
      ansible.builtin.include_role:
        name: inventory