---
- name: Enable the http action senor in the Instana agent
  hosts: tag_Type_ml_demo
  become: true
  gather_facts: false

  tasks:

    - name: Edit the file
      ansible.builtin.blockinfile:
        path: /opt/instana/agent/etc/instana/configuration.yaml
        insertafter: "^#com.instana.plugin.action.http |
                          enabled: true"
        block: |
            com.instana.plugin.action.http:
              enabled: true
        state: present
