- name: F5 daily demo
  hosts: localhost
  connection: local

  tasks:

    - name: Include the vpc role
      tags:
        - create
      ansible.builtin.include_role:
        name: vpc

    - name: Include the vm role
      tags:
        - create
      ansible.builtin.include_role:
        name: vm

    - name: Include the inventory role
      tags:
        - create
      ansible.builtin.include_role:
        name: inventory

    - name: F5 User Interface
      loop: "{{ instance_info['instances'] }}"
      tags:
        - create
      ansible.builtin.debug:
        msg: "https://{{ item['public_dns_name'] }}:8443"

    - name: F5 IP Address
      loop: "{{ instance_info['instances'] }}"
      tags:
        - create
      ansible.builtin.debug:
        msg: "{{ item['public_ip_address'] }}"

    - name: Include the vm role
      tags:
        - remove
      ansible.builtin.include_role:
        name: vm

    - name: Include the vpc role
      tags:
        - remove
      ansible.builtin.include_role:
        name: vpc

    - name: Include the inventory role
      tags:
        - remove
      ansible.builtin.include_role:
        name: inventory
