- name: F5 daily demo
  hosts: localhost
  connection: local

  tasks:

    - name: Creating the F5 Daily Demo
      tags:
        - create
      block:

        - name: Include the vpc role
          ansible.builtin.include_role:
            name: vpc

        - name: Include the vm role
          ansible.builtin.include_role:
            name: vm

        - name: Include the inventory role
          ansible.builtin.include_role:
            name: inventory

        - name: F5 User Interface
          ansible.builtin.debug:
            msg: "https://{{ ec2_vms.instances[0].public_dns_name }}:8443"

        - name: F5 IP Address
          ansible.builtin.debug:
            msg: "{{ ec2_vms.instances[0].public_ip_address }}"

    - name: Removing the F5 Daily Demo
      tags:
        - remove
      block:

        - name: Include the vm role
          ansible.builtin.include_role:
            name: vm

        - name: Include the vpc role
          ansible.builtin.include_role:
            name: vpc

        - name: Include the inventory role
          ansible.builtin.include_role:
            name: inventory
