- name: Setup demo
  hosts: localhost
  gather_facts: false

  vars:
    aap_validate_certs: true
    aap_hostname: ericames.ddns.net

  vars_files:
    - files/secrets.yml

  tasks:

    - name: Include configurations
      ansible.builtin.include_vars: files/config_as_code/config.yml

    - name: Demo Components
      vars:
        meta_dependency_check: false  # noqa: var-naming[no-role-prefix]
      ansible.builtin.include_role:
        name: infra.aap_configuration.dispatch

    - name: Print Message
      when: user_message is defined
      ansible.builtin.debug:
        msg: "{{ user_message }}"
