- name: Setup demo
  hosts: localhost
  gather_facts: false

  tasks:

    - name: Create a new token using username/password
      ansible.controller.token:
        controller_host: "{{ lookup('ansible.builtin.env', 'CONTROLLER_HOST') }}"
        controller_username: "{{ lookup('ansible.builtin.env', 'CONTROLLER_USERNAME') }}"
        controller_password: "{{ lookup('ansible.builtin.env', 'CONTROLLER_PASSWORD') }}"
        validate_certs: false
        description: F5 Setup
        scope: write
        state: present

    - name: Include configurations
      ansible.builtin.include_vars: files/config_as_code/config.yml

    - name: Demo Components
      vars:
        meta_dependency_check: false  # noqa: var-naming[no-role-prefix]
      ansible.builtin.include_role:
        name: infra.aap_configuration.dispatch

    - name: Print Message
      when: user_message is defined
      ansible.builtin.debug:
        msg: "{{ user_message }}"

    - name: Remove my token
      ansible.controller.token:
        controller_host: "{{ lookup('ansible.builtin.env', 'CONTROLLER_HOST') }}"
        controller_oauthtoken: "{{ controller_token }}"
        existing_token: "{{ controller_token }}"
        validate_certs: false
        state: absent
